apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: notification-service
profiles:
  - name: local
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:7.6-jdk11-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: devstream-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
            setValues:
              environment: local
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/local.yaml
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      artifacts:
        - image: notification-service
          jib:
            type: gradle
            project: service
    manifests:
      helm:
        releases:
          - name: notification-service
            createNamespace: true
            chartPath: helm/application
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/local.yaml
            setValues:
              environment: local
              net.readinessProbe.initialDelaySeconds: 60
              pullPolicy: IfNotPresent
              postgres.enabled: "true"
              ingress.enabled: "true"
            setValueTemplates:
              image.repository: notification-service
              image.tag: notification-service
    deploy:
      statusCheckDeadlineSeconds: 60
      tolerateFailuresUntilDeadline: true
      helm: {}
    portForward:
      - resourceType: service
        resourceName: notification-service
        namespace: devstream
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: notification-service-postgres
        namespace: devstream
        port: 5432
        localPort: 5438
  - name: dev
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:7.6-jdk11-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: devstream-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
            setValues:
              environment: dev
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/dev.yaml
  - name: staging
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:7.6-jdk11-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: devstream-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
            setValues:
              environment: staging
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/staging.yaml
  - name: prod
    build:
      googleCloudBuild:
        projectId: devstream-shared-services-4179
        gradleImage: gradle:7.6-jdk11-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/devstream-shared-services-4179/application/devstream-notification-service
          jib:
            type: gradle
            project: service
    deploy:
      helm:
        releases:
          - name: devstream-notification-service
            createNamespace: true
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_devstream_shared_services_4179_application_devstream_notification_service}}"
            setValues:
              environment: prod
            valuesFiles:
              - helm/application/values.yaml
              - helm/application/prod.yaml
