apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: message
  rules:
    - actions: [ "view" ]
      roles:
        - notification-admin
      effect: EFFECT_ALLOW
    - actions: ["send"]
      roles:
        - notification-admin
        - notification-sender
      effect: EFFECT_ALLOW