apiVersion: v1
kind: Service
metadata:
  name: notification-service-postgres
  namespace: {{ .Values.namespace | default "devstream" }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30204
  sessionAffinity: None
  type: NodePort